application:
  host: 0.0.0.0
database:
  require_ssl: true
email_client:
  base_url: "https://api.postmarkapp.com"
  # The single sender email authorized on Postmark
  sender_email: "something@gmail.com"
